version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
      - LOG_CHANNEL=stderr
    depends_on:
      - node

  node:
    image: node:18-alpine
    working_dir: /var/www/html
    volumes:
      - ./public/build:/var/www/html/public/build
    command: npm install && npm run build
    ports:
      - "5173:5173"
